### ISSUE TITLE
Function self.getPyramidLevels() doesn't exist

### ISSUE THREAD

**Issue by koegl** [fepegar/slicer-niftyreg#1]
https://github.com/fepegar/slicer-niftyreg/blob/2dfb8c74cb635b3df1e4e537d0c59a68a67fe3cd/NiftyReg.py#L342

self.getPyramidLevels() doesn't exist.

Commenting this line and simply not setting `ln` and `lp` works.

From the documentation it is not obvious to me what `ln` and `lp` are in the GUI.

I'd be happy to provide this function in a pull request if you could tell me what those values are supposed to be.

**Comment by fepegar** [comment]
Hi, @koegl. This repository is very old and I can't remember much about it. I think it never really worked. It probably comes from [fepegar/slicer-blockmatching](https://github.com/fepegar/slicer-blockmatching/blob/master/Blockmatching.py).

`ln` and `lp` are NiftyReg (actually, `reg_aladin`) [parameters](https://github.com/KCL-BMEIS/niftyreg/blob/a328efb3a2f8ea4b47cf0f7b581d983a570a1ffd/reg-apps/reg_aladin.cpp#L64-L65).
